{% set name = "cssutils" %}
{% set version = "2.15.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e9739237f3915037dacba787c4b58f280e3ec5d9864953e185bf23d40ff7d021

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - csscapture=cssutils.scripts.csscapture:main
    - csscombine=cssutils.scripts.csscombine:main
    - cssparse=cssutils.scripts.cssparse:main

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools_scm >=3.4.1
    - setuptools >=77
    - coherent.licensed
  run:
    - python >={{ python_min }}
    - more-itertools
    - encutils

test:
  requires:
    - python {{ python_min }}
    - pip
  imports:
    - cssutils
  commands:
    - pip check
    - csscapture --help
    - csscombine --help
    - cssparse --help

about:
  home: https://github.com/jaraco/cssutils
  license: LGPL-3.0-only
  license_file:
    - LICENSE
  summary: A CSS Cascading Style Sheets library for Python

extra:
  recipe-maintainers:
    - vamega
    - thewchan
