{% set name = "cssutils" %}
{% set version = "2.0.0" %}
{% set sha256 = "984b5dbe3a2a0483d7cb131609a17f4cbaa34dda306c419924858a88588fed7c" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python <3
    - pip
  run:
    - python <3

test:
  imports:
    - cssutils

about:
  home: http://cthedot.de/cssutils/
  license: LGPL3
  license_file: 
    - COPYING 
    - COPYING.LESSER 

  summary: A CSS Cascading Style Sheets library for Python

extra:
  recipe-maintainers:
    - vamega
