{% set name = "cssutils" %}
{% set version = "1.0.2" %}
{% set sha256 = "a2fcf06467553038e98fea9cfe36af2bf14063eb147a70958cfcaa8f5786acaf" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 1000 
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python <3
    - pip
  run:
    - python <3

test:
  imports:
    - cssutils

about:
  home: http://cthedot.de/cssutils/
  license: LGPL3
  summary: A CSS Cascading Style Sheets library for Python

extra:
  recipe-maintainers:
    - vamega
