{% set name = "cssutils" %}
{% set version = "2.11.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0563a76513b6af6eebbe788c3bf3d01c920e46b3f90c8416738c5cfc773ff8e2

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - csscapture=cssutils.scripts.csscapture:main
    - csscombine=cssutils.scripts.csscombine:main
    - cssparse=cssutils.scripts.cssparse:main

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools_scm >=3.4.1
    - setuptools >=61.2
    - tomli
  run:
    - python >={{ python_min }}
    - more-itertools

test:
  requires:
    - python {{ python_min }}
    - pip
  imports:
    - cssutils
  commands:
    - pip check
    - csscapture --help
    - csscombine --help
    - cssparse --help

about:
  home: https://github.com/jaraco/cssutils
  license: LGPL-3.0-only
  license_file:
    - LICENSE
  summary: A CSS Cascading Style Sheets library for Python

extra:
  recipe-maintainers:
    - vamega
    - thewchan
