{% set name = "cssutils" %}
{% set version = "2.11.1" %}
{% set sha256 = "0563a76513b6af6eebbe788c3bf3d01c920e46b3f90c8416738c5cfc773ff8e2" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools_scm >=6.4.2
  run:
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - cssutils

about:
  home: http://cthedot.de/cssutils/
  license: LGPL-3.0-only
  license_file:
    - COPYING
    - COPYING.LESSER

  summary: A CSS Cascading Style Sheets library for Python

extra:
  recipe-maintainers:
    - vamega
